### PR TITLE
Mod5 edits

### PR DESCRIPTION
**Pull request by Mcast77**
I added a CONTRIBUTING file and edited the README file.

### CODE REVIEW

**Review by Mcast77 — COMMENTED** [review]
Can some one check if this is ok

**Review by Mcast77 — COMMENTED** [review]
Did I spell everything correctly

**Review by Mcast77 — COMMENTED** [review]
Did I spell everything correctly.

**Review by Mcast77 — COMMENTED** [review]
Can someone review this

**Review by epfor3 — APPROVED** [review]

**Pull request merged**
